use_frameworks!

platform :ios, '9.0'

target 'TPNetworking_Example' do
  pod 'TPNetworking', :path => '../'
  pod 'TPJsonModel', :git => 'https://github.com/Topredator/TPJsonModel.git'
  
  target 'TPNetworking_Tests' do
    inherit! :search_paths

    
  end
end
